runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

  # Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
static_files: \1
upload: .+\.(gif|png|jpg)$
application_readable: true

- url: /assets/images
static_dir: assets/images
